os: linux
dist: bionic
sudo: required
dist: trusty
before_install:
- sudo apt-get install -y --no-install-recommends texlive-full chktex
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build bilety.tex
- chktex bilety.tex >linter.txt
